### ISSUE TITLE
xoops version

### ISSUE THREAD

**Issue by Zap-English** [XoopsModules25x/tdmmoney#8]
This update is for xoops v2.5.8
I have 2.5.6

**Comment by mambax7** [comment]
You should upgrade to the latest XOOPS version - currently it is 2.5.9
2.5.6 is not supported anymore.

**Comment by Zap-English** [comment]
My website still doesn't work correctly after the last update. And I'm not updating again, because sure as shit, everything will go wrong with every module

When I asked for this module to be fixed 2.5.6 was the latest version
